### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by dgellow** [MattLLLLL/MDatePickerView#2]
Hi,

I'm a bit confused by the licensing, I see that the readme says "MDatePickerView is available under the MIT license", but I don't see a copy of the license anywhere in the sources, and noticed that every swift file has the following header:
> //  Created by Matt on 2020/1/9.
> //  Copyright © 2020 Matt. All rights reserved.
> //

For reference, the [common version of the MIT license](https://en.wikipedia.org/wiki/MIT_License) has the following section in the middle:

> The above copyright notice and this permission notice shall be included in all
> copies or substantial portions of the Software.

As I understand it, the full text of the license should be somewhere in this repository, and conflicts with the header in source files. Could you clarify?

**Comment by MattLLLLL** [comment]
License added.
