### ISSUE TITLE
mdate.from and to..

### ISSUE THREAD

**Issue by daviddelmonte** [MattLLLLL/MDatePickerView#7]
are not recognized..

```
mdate.from = 1980
 mdate.to = 2100
```

output: 
`Value of type 'MDatePickerView' has no member 'from'`
`Value of type 'MDatePickerView' has no member 'to'`

It could be nice - please advise if I'm missing something.. I installed through CocoaPods

**Comment by MattLLLLL** [comment]
Just now I updated the kit. Upgraded v1.2.3

**Comment by daviddelmonte** [comment]
perfect now. Thanks Matt
